#!/usr/bin/env bash

set -o nounset
set -o errexit

function banner() {
    cat << EOF
Generate images from RGB triplets of ImageMagick -fx "scripts"
echo and save the scripts + parameters used for reproductibility
EOF
}

function usage() {
    echo Usage: im-fxrun \[options\] \[red\] \[green\] \[blue\] \[extra\]
}

function help_text(){
    cat << EOF
$(banner)

$(usage)

Options:
-s, --size          size of image
-c, --colorspace    colorspace of image
-h, --help          this help
EOF
}

function err_file_notexist(){
    1>&2 printf ''\''%s'\'': file does not exist\n' "$1"
    exit 1
}

function err_file_exist(){
    1>&2 printf ''\''%s'\'': file exists\n' "$1"
    exit 1
}

function err_no_image(){
    1>&2 echo error generating image or saving auxiliary data: cleaning up
    set +o nounset
    rm "$filename"
    for ext in rcol bcol gcol extra
    do
        rm "$filename"."$ext"
    done
    exit 1
}

components=( )

if [[ ${#@} == 0 ]]
then
    help_text
    exit 1
fi

ARGS="$(getopt --options h.c:,s: --long help,colorspace:,size: "$@")"
eval set -- "$ARGS"
while [[ ${#@} != 0 ]]
do
    case "$1" in
    -s | --size)
        size="$2"
        shift 2
        ;;
    -c | --colorspace)
        colorspace="$2"
        shift 2
        ;;
    -h | --help)
        help_text
        exit 1
        ;;
    --)
        shift
        ;;
    *)
        set +o nounset
        if [[ ! -e "$1" ]]
        then
            err_file_notexist "$1"
        fi
        set -o nounset
        components+=("$1")
        shift
        ;;
    esac
done

if [[ (${#components[@]} == 4) ]]
then
    source "${components[3]}"
elif [[ ${#components[@]} != 3 ]]
then
    1>&2 printf 'Expected 3 or 4 components, got %s\n' ${#components[@]}
    exit 1
fi

filename="$(mktemp "$(date +%s)"-XXXX --suffix .png)"
for ext in rcol gcol bcol extra
do
    [[ -e "$filename"."$ext" ]] && err_file_exist "$filename"."$ext"
    touch "$filename"."$ext"
done

trap 'err_no_image' ERR EXIT

magick -size "$size" -colorspace "$colorspace" canvas:black \
-channel R -fx @"${components[0]}" \
-channel G -fx @"${components[1]}" \
-channel B -fx @"${components[2]}" \
"$filename"

cat "${components[0]}" > "$filename".rcol
cat "${components[1]}" > "$filename".gcol
cat "${components[2]}" > "$filename".bcol

cat << EOF > "$filename".extra
size=$size
colorspace=$colorspace
EOF

trap '' ERR EXIT
